#!/usr/bin/expect -f

set timeout -1

spawn qemu-system-x86_64 --enable-kvm -kernel vmlinux -append "console=ttyS0 root=/dev/nvme0n1 init=/sbin/sh" -smp 1 -m 1G  -display none -serial stdio -drive file=testdisk.img,if=none,id=nvme -device nvme,drive=nvme,serial=disk -drive file=vac.img,if=none,id=nvme1 -device nvme,drive=nvme1,serial=disk1 -no-reboot

expect "~ # "
send "mkdir /tmp\n"

expect "~ # "
send "mkdir /tmp/mnt\n"

expect "~ # "
send "mount -t vfat /dev/nvme1n1 /tmp/mnt\n"

expect "~ # "
send "insmod /tmp/mnt/xvac.ko\n"

expect "~ # "
send "insmod /tmp/mnt/irqbypass.ko\n"

expect "~ # "
send "insmod /tmp/mnt/kvm-a.ko\n"

expect "~ # "
send "reboot -f\n"
